name: derwichtigstejob
favicon: null
layout_spectrum: 0.06001629075035453
typography_spectrum: 0.8106136471033096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25507516390644014
  lightness: 0.045536399353295565
  saturation: 0.08149995352141559
  rhythmicContrast: 0.2109045705292374
purpose: []
